//! Fuzz target: `rnp::decrypt` against arbitrary byte streams.
//!
//! Each iteration constructs a fresh `Context` (cheap), passes the
//! fuzzer-generated bytes as ciphertext, and asserts that the call
//! either succeeds with a real plaintext or fails cleanly via `Err`
//! — never panics, never reads/writes out of bounds.

#![no_main]

use libfuzzer_sys::fuzz_target;
use rnp::Context;

fuzz_target!(|data: &[u8]| {
    let ctx = match Context::new() {
        Ok(c) => c,
        Err(_) => return,
    };
    let _ = rnp::decrypt(&ctx, data);
});
