//! Fuzz target: packet-dump a signature blob, then walk its subpackets.
//!
//! Each iteration takes the fuzzer-generated bytes as a standalone
//! signature packet, runs `dump_packets_bytes_to_json` to exercise the
//! parser, and asserts no panics. The dump path covers the same packet
//! parser librnp uses for key/message handling.

#![no_main]

use libfuzzer_sys::fuzz_target;
use rnp::Context;

fuzz_target!(|data: &[u8]| {
    let _ = rnp::dump_packets_bytes_to_json(data, rnp::JsonDumpFlags::default());

    // Also exercise key_load path — many signature blobs have key
    // structures embedded or adjacent.
    let ctx = match Context::new() {
        Ok(c) => c,
        Err(_) => return,
    };
    let _ = ctx.load_keys(rnp::KeyringFormat::Gpg, data, rnp::LoadSaveFlags::PUBLIC);
});
